# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\cn-wilsonshi\Desktop\work\translation\自动国际化\view.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(408, 300)
        self.react_label = QtWidgets.QLabel(Form)
        self.react_label.setGeometry(QtCore.QRect(40, 40, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.react_label.setFont(font)
        self.react_label.setObjectName("react_label")
        self.dic_label = QtWidgets.QLabel(Form)
        self.dic_label.setGeometry(QtCore.QRect(40, 100, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dic_label.setFont(font)
        self.dic_label.setObjectName("dic_label")
        self.startButton = QtWidgets.QPushButton(Form)
        self.startButton.setGeometry(QtCore.QRect(80, 230, 241, 51))
        self.startButton.setObjectName("startButton")
        self.react_lineEdit = QtWidgets.QLineEdit(Form)
        self.react_lineEdit.setGeometry(QtCore.QRect(170, 40, 181, 21))
        self.react_lineEdit.setObjectName("react_lineEdit")
        self.dic_lineEdit = QtWidgets.QLineEdit(Form)
        self.dic_lineEdit.setGeometry(QtCore.QRect(170, 100, 181, 21))
        self.dic_lineEdit.setObjectName("dic_lineEdit")
        self.tag_label = QtWidgets.QLabel(Form)
        self.tag_label.setGeometry(QtCore.QRect(40, 70, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tag_label.setFont(font)
        self.tag_label.setObjectName("tag_label")
        self.tag_lineEdit = QtWidgets.QLineEdit(Form)
        self.tag_lineEdit.setGeometry(QtCore.QRect(170, 70, 181, 21))
        self.tag_lineEdit.setObjectName("tag_lineEdit")
        self.ac_label = QtWidgets.QLabel(Form)
        self.ac_label.setGeometry(QtCore.QRect(40, 130, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ac_label.setFont(font)
        self.ac_label.setObjectName("ac_label")
        self.creator_label = QtWidgets.QLabel(Form)
        self.creator_label.setGeometry(QtCore.QRect(40, 160, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.creator_label.setFont(font)
        self.creator_label.setObjectName("creator_label")
        self.creator_lineEdit = QtWidgets.QLineEdit(Form)
        self.creator_lineEdit.setGeometry(QtCore.QRect(170, 160, 181, 21))
        self.creator_lineEdit.setObjectName("creator_lineEdit")
        self.ac_lineEdit = QtWidgets.QLineEdit(Form)
        self.ac_lineEdit.setGeometry(QtCore.QRect(170, 130, 181, 21))
        self.ac_lineEdit.setObjectName("ac_lineEdit")
        self.outputpath_label = QtWidgets.QLabel(Form)
        self.outputpath_label.setGeometry(QtCore.QRect(40, 190, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.outputpath_label.setFont(font)
        self.outputpath_label.setObjectName("outputpath_label")
        self.outputpath_lineEdit = QtWidgets.QLineEdit(Form)
        self.outputpath_lineEdit.setGeometry(QtCore.QRect(170, 190, 181, 21))
        self.outputpath_lineEdit.setObjectName("outputpath_lineEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "React自动国际化 V 1.0.2"))
        self.react_label.setText(_translate("Form", "React文件路径"))
        self.dic_label.setText(_translate("Form", "字典路径(选填)"))
        self.startButton.setText(_translate("Form", "开始国际化"))
        self.tag_label.setText(_translate("Form", "通配符标识"))
        self.ac_label.setText(_translate("Form", "App Code"))
        self.creator_label.setText(_translate("Form", "操作人"))
        self.outputpath_label.setText(_translate("Form", "输出（选填）"))
