# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\cn-wilsonshi\Desktop\work\unity_tool\musicApp\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_From(object):
    def setupUi(self, From):
        From.setObjectName("From")
        From.resize(600, 400)
        self.search_label = QtWidgets.QLabel(From)
        self.search_label.setGeometry(QtCore.QRect(120, 20, 81, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.search_label.setFont(font)
        self.search_label.setObjectName("search_label")
        self.search_lineEdit = QtWidgets.QLineEdit(From)
        self.search_lineEdit.setGeometry(QtCore.QRect(200, 20, 140, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.search_lineEdit.setFont(font)
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.search_pushButton = QtWidgets.QPushButton(From)
        self.search_pushButton.setGeometry(QtCore.QRect(360, 20, 61, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.search_pushButton.setFont(font)
        self.search_pushButton.setObjectName("search_pushButton")
        self.local_pushButton = QtWidgets.QPushButton(From)
        self.local_pushButton.setGeometry(QtCore.QRect(520, 360, 40, 28))
        self.local_pushButton.setObjectName("local_pushButton")
        self.timestart_label = QtWidgets.QLabel(From)
        self.timestart_label.setGeometry(QtCore.QRect(480, 320, 36, 22))
        self.timestart_label.setObjectName("timestart_label")
        self.timeend_label = QtWidgets.QLabel(From)
        self.timeend_label.setGeometry(QtCore.QRect(540, 320, 36, 22))
        self.timeend_label.setObjectName("timeend_label")
        self.horizontalSlider = QtWidgets.QSlider(From)
        self.horizontalSlider.setGeometry(QtCore.QRect(40, 320, 421, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.none_label = QtWidgets.QLabel(From)
        self.none_label.setGeometry(QtCore.QRect(520, 320, 16, 22))
        self.none_label.setObjectName("none_label")
        self.play_pushButton = QtWidgets.QPushButton(From)
        self.play_pushButton.setGeometry(QtCore.QRect(280, 360, 40, 28))
        self.play_pushButton.setObjectName("play_pushButton")
        self.next_pushButton = QtWidgets.QPushButton(From)
        self.next_pushButton.setGeometry(QtCore.QRect(340, 360, 40, 28))
        self.next_pushButton.setObjectName("next_pushButton")
        self.prev_pushButton = QtWidgets.QPushButton(From)
        self.prev_pushButton.setGeometry(QtCore.QRect(220, 360, 40, 28))
        self.prev_pushButton.setObjectName("prev_pushButton")
        self.playmode_pushButton = QtWidgets.QPushButton(From)
        self.playmode_pushButton.setGeometry(QtCore.QRect(40, 360, 40, 28))
        self.playmode_pushButton.setObjectName("playmode_pushButton")
        self.listWidget = QtWidgets.QListWidget(From)
        self.listWidget.setGeometry(QtCore.QRect(30, 60, 541, 241))
        self.listWidget.setMinimumSize(QtCore.QSize(0, 241))
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(From)
        QtCore.QMetaObject.connectSlotsByName(From)

    def retranslateUi(self, From):
        _translate = QtCore.QCoreApplication.translate
        From.setWindowTitle(_translate("From", "音乐播放器"))
        self.search_label.setText(_translate("From", "搜索网易："))
        self.search_pushButton.setText(_translate("From", "搜索"))
        self.local_pushButton.setText(_translate("From", "本地"))
        self.timestart_label.setText(_translate("From", "00:00"))
        self.timeend_label.setText(_translate("From", "00:00"))
        self.none_label.setText(_translate("From", "/"))
        self.play_pushButton.setText(_translate("From", "play"))
        self.next_pushButton.setText(_translate("From", "next"))
        self.prev_pushButton.setText(_translate("From", "prev"))
        self.playmode_pushButton.setText(_translate("From", "mode"))
