# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\cn-wilsonshi\Desktop\work\unity_tool\WilsonTrans\tranView.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(813, 471)
        self.text_output_Browser = QtWidgets.QTextBrowser(Form)
        self.text_output_Browser.setGeometry(QtCore.QRect(450, 120, 341, 301))
        self.text_output_Browser.setObjectName("text_output_Browser")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(380, 60, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(30, 120, 341, 301))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.lineEdit, self.pushButton)
        Form.setTabOrder(self.pushButton, self.text_output_Browser)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "中英翻译器"))
        self.pushButton.setText(_translate("Form", "翻译"))
